---
- name: "Install software properties common"
  apt:
    name: "software-properties-common"
    state: present

- name: "Install ppa certbot repository"
  apt_repository:
    repo: "ppa:certbot/certbot"
    state: present
    update_cache: no
    #    validate_certs: no

- name: "Install certbot packages"
  apt:
    name:
      - "certbot"
      - "python3-certbot-nginx"
    state: present
    update_cache: yes
